name: Build, Test and Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DOTNET_VERSION: '8.0.x'
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  NUGET_API_KEY: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Install SonarCloud scanner
      run: dotnet tool install --global dotnet-sonarscanner
    
    - name: SonarCloud Begin Analysis
      run: |
        dotnet sonarscanner begin /k:"TU_PROYECTO_SONARCLOUD" /o:"TU_ORG_SONARCLOUD" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io"
    
    - name: Build and Test
      run: |
        dotnet build --configuration Release
        dotnet test --configuration Release --collect:"XPlat Code Coverage" --logger trx
    
    - name: SonarCloud End Analysis
      run: dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
    
    - name: Pack NuGet packages
      run: |
        dotnet pack ./Payment.Domain/Payment.Domain.csproj --configuration Release --output ./artifacts
        dotnet pack ./ATM.Domain/ATM.Domain.csproj --configuration Release --output ./artifacts
    
    - name: Publish NuGet packages to GitHub Packages
      run: |
        dotnet nuget push ./artifacts/*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json